trigger:
- main

pool:
  vmImage: 'macOS-latest'

stages:
- stage: Development
  jobs:
  - job: Deploy
    steps:
    - task: UsePythonVersion@0
      displayName: "Use Python 3"
      inputs:
        versionSpec: '3.x'
        addToPath: true
        architecture: 'x64'
    - task: CmdLine@2
      displayName: "Install pip dependancies"
      inputs:
        script: |
          python -m venv ./venv
          pip install -r requirements.txt
    - task: Pulumi@1 # needs env variable 'pulumi.access.token'
      displayName: "Deploy Infrastructure"
      inputs:
        azureSubscription: 'Azure Purple Trial'
        command: 'up'
        args: '--yes'
        stack: 'dev'

- stage: Production
  jobs:
  - deployment: deploy
    environment: Production
    strategy:
     runOnce:
      deploy:
        steps:
        - task: CmdLine@2
          inputs:
            script: 'echo hello world'
