trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Development
  jobs:
  - job: Deploy
    steps:
    - task: CmdLine@2
      inputs:
        script: 'echo hello world'

- stage: Production
  jobs:
  - job: Deploy
    steps:
    - task: CmdLine@2
      inputs:
        script: 'echo hello world'
