trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Development
  jobs:
  - job: Deploy
    steps:
    - task: Pulumi@1 # needs env variable 'pulumi.access.token'
      displayName: "Deploy Infrastructure"
      inputs:
        azureSubscription: 'Azure Purple Trial'
        command: 'up'
        args: '--yes'
        stack: 'dev'

- stage: Production
  jobs:
  - deployment: deploy
    environment: Production
    strategy:
     runOnce:
      deploy:
        steps:
        - task: CmdLine@2
          inputs:
            script: 'echo hello world'
