trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Development
  jobs:
  - job: Deploy
    steps:
    - task: CmdLine@2
      inputs:
        script: 'echo hello world'

- stage: Production
  jobs:
  - job: Deploy
    steps:
    - task: ManualIntervention@8
      inputs:
        instructions: 'Do you wish to deploy into production?'
    - task: CmdLine@2
      inputs:
        script: 'echo hello world'
